version = "3.7.9"
runner.dialect = scala3

maxColumn = 100
align.preset = most

rewrite.rules = [imports]
rewrite.imports.sort = ascii
rewrite.imports.expand = true

continuationIndent.defnSite = 2
continuationIndent.callSite = 2
