# Declare the variable pointing to your environment secret file
@apiKey = {{$dotenv TICKETMASTER_API_KEY}}

### Get Local Events in Ireland from Ticketmaster Discovery API
GET https://app.ticketmaster.com/discovery/v2/events.json?countryCode=IE&apikey={{apiKey}}
Accept: application/json